name: CI/CD
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: '10.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs a set of commands to build
      - name: Build
        run: npm run build
    # sotre the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: public
          path: ./public
  # deploy job
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully
    needs: [build]
    steps:
      # building the app before deploy
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '10.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # build the app
      - name: Build the app artifact for prod
        run: npm run build
      # ddeploy the app artifact to firebase
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
